name: wallanoti

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres.${HOSTNAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wallanoti_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/wallanoti.sql:/docker-entrypoint-initdb.d/wallanoti.sql
    ports:
      - "5432:5432"
    networks:
      - wallanoti

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - wallanoti

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wallanoti

networks:
  wallanoti:
    driver: bridge