name: wallanoti

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres.${HOSTNAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wallanoti_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/wallanoti.sql:/docker-entrypoint-initdb.d/wallanoti.sql
    ports:
      - "5432:5432"
    networks:
      - wallanoti

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - wallanoti

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wallanoti

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wallanoti-api
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080;https://+:8081
      ConnectionStrings__DefaultConnection: Host=postgres;Database=wallanoti_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      Redis__Configuration: redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - wallanoti

networks:
  wallanoti:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
