CREATE TABLE IF NOT EXISTS users (
    "Id" BIGINT PRIMARY KEY,
    "UserName" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts (
    "Id" UUID PRIMARY KEY,
    "UserId" BIGINT NOT NULL,
    "Name" VARCHAR(50) NOT NULL,
    "Url" VARCHAR(200) NOT NULL,
    "CreateAt" TIMESTAMP NOT NULL,
    "LastSearch" TIMESTAMP NULL,
    CONSTRAINT alerts_users_FK FOREIGN KEY ("UserId") REFERENCES users("Id") ON DELETE CASCADE ON UPDATE CASCADE
);